services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: server
      POSTGRES_PASSWORD: abcdef
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
